swagger: '2.0'
info:
  title: API Demo
  version: '1.0'
basePath: /v1
schemes:
  - https
  - http
paths:
  /patent/trend1:
    post:
      summary: 专利趋势
      operationId: patent_trend1
      parameters:
        - name: user
          in: body
          required: true
          schema:
            $ref: '#/definitions/Trend1Req'
      responses:
        '200':
          description: success
          schema:
            $ref: '#/definitions/Trend1Res'
        '400':
          description: Invalid input
definitions:
  Trend1Req:
    type: object
    properties:
      industry:
        type: string
  Trend1Res:
    type: object
    properties:
      data:
        type: array
        properties:
          year:
            type: string
          num:
            type: integer