swagger: '2.0'
info:
  title: API Demo
  version: '1.0'
basePath: /v1
schemes:
  - https
  - http
paths:
  /patent/trend1:
    options:
      summary: CORS support for 专利趋势1
      operationId: patent_trend1_options
      responses:
        '200':
          description: CORS preflight request successful
    post:
      summary: 专利趋势1
      operationId: patent_trend1
      produces:
        - application/json
      consumes:
        - application/json
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/Trend1Req'
      responses:
        '200':
          description: success
          schema:
            $ref: '#/definitions/Trend1Res'
        '400':
          description: Invalid input
  /patent/trend2:
    options:
      summary: CORS support for 专利趋势2
      operationId: patent_trend2_options
      responses:
        '200':
          description: CORS preflight request successful
    post:
      summary: 专利趋势2
      operationId: patent_trend2
      produces:
        - application/json
      consumes:
        - application/json
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/Trend2Req'
      responses:
        '200':
          description: success
          schema:
            $ref: '#/definitions/Trend2Res'
        '400':
          description: Invalid input
  /patent/applicant:
    options:
      summary: CORS support for 申请人分析
      operationId: patent_applicant_options
      responses:
        '200':
          description: CORS preflight request successful
    post:
      summary: 申请人分析
      operationId: patent_applicant
      produces:
        - application/json
      consumes:
        - application/json
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/ApplicantReq'
      responses:
        '200':
          description: success
          schema:
            $ref: '#/definitions/ApplicantRes'
        '400':
          description: Invalid input
  /patent/area:
    options:
      summary: CORS support for 地域分析
      operationId: patent_area_options
      responses:
        '200':
          description: CORS preflight request successful
    post:
      summary: 地域分析
      operationId: patent_area
      produces:
        - application/json
      consumes:
        - application/json
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/AreaReq'
      responses:
        '200':
          description: success
          schema:
            $ref: '#/definitions/AreaRes'
        '400':
          description: Invalid input
  /patent/type:
    options:
      summary: CORS support for 类型分析
      operationId: patent_type_options
      responses:
        '200':
          description: CORS preflight request successful
    post:
      summary: 类型分析
      operationId: patent_type
      produces:
        - application/json
      consumes:
        - application/json
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/TypeReq'
      responses:
        '200':
          description: success
          schema:
            $ref: '#/definitions/TypeRes'
        '400':
          description: Invalid input
  /patent_report/save:
    options:
      summary: CORS support for 报告保存
      operationId: patent_report_save_options
      responses:
        '200':
          description: CORS preflight request successful
    post:
      summary: 报告保存
      operationId: patent_report_save
      produces:
        - application/json
      consumes:
        - application/json
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/PatentReportReq'
      responses:
        "200":
          description: success
          content:
            application/json:
              schema:
                $ref: '#/definitions/PatentReportRes'
        "400":
          description: Invalid input
          content: {}
      x-codegen-request-body-name: body
      x-openapi-router-controller: swagger_server.controllers.default_controller
  /patent_report_detail/save:
    options:
      summary: CORS support for 报告详情保存
      operationId: patent_report_detail_save_options
      responses:
        '200':
          description: CORS preflight request successful
    post:
      summary: 报告详情保存
      operationId: patent_report_detail_save
      produces:
        - application/json
      consumes:
        - application/json
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/PatentReportDetailReq'
      responses:
        "200":
          description: success
          content:
            application/json:
              schema:
                $ref: '#/definitions/PatentReportDetailRes'
        "400":
          description: Invalid input
          content: {}
      x-codegen-request-body-name: body
      x-openapi-router-controller: swagger_server.controllers.default_controller
  /patent/technology:
    options:
      summary: CORS support for 技术构成分析
      operationId: patent_technology_options
      responses:
        '200':
          description: CORS preflight request successful
    post:
      summary: 技术构成分析
      operationId: patent_technology
      produces:
        - application/json
      consumes:
        - application/json
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/TechnologyReq'
      responses:
        '200':
          description: success
          schema:
            $ref: '#/definitions/TechnologyRes'
        '400':
          description: Invalid input
  /patent/concentration:
    options:
      summary: CORS support for 集中度分析
      operationId: patent_concentration_options
      responses:
        '200':
          description: CORS preflight request successful
    post:
      summary: 集中度分析
      operationId: patent_concentration
      produces:
        - application/json
      consumes:
        - application/json
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/ConcentrationReq'
      responses:
        '200':
          description: success
          schema:
            $ref: '#/definitions/ConcentrationRes'
        '400':
          description: Invalid input
  /report/list:
    options:
      summary: CORS support for 报告列表
      operationId: report_list_options
      responses:
        '200':
          description: CORS preflight request successful
    post:
      summary: 报告列表
      operationId: report_list
      produces:
        - application/json
      consumes:
        - application/json
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/ListReq'
      responses:
        '200':
          description: success
          schema:
            $ref: '#/definitions/ListRes'
        '400':
          description: Invalid input
  /report/detail:
    options:
      summary: CORS support for 报告详情
      operationId: report_detail_options
      responses:
        '200':
          description: CORS preflight request successful
    post:
      summary: 报告详情
      operationId: report_detail
      produces:
        - application/json
      consumes:
        - application/json
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/DetailReq'
      responses:
        '200':
          description: success
          schema:
            $ref: '#/definitions/DetailRes'
        '400':
          description: Invalid input
  /report/delete:
    options:
      summary: CORS support for 删除报告
      operationId: report_delete_options
      responses:
        '200':
          description: CORS preflight request successful
    post:
      summary: 删除报告
      operationId: report_delete
      produces:
        - application/json
      consumes:
        - application/json
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/DeleteReq'
      responses:
        '200':
          description: success
        '400':
          description: Invalid input
definitions:
  Trend1Req:
    type: object
    properties:
      industry:
        type: string
      area:
        type: string
      applicant:
        type: string
      key:
        type: string
      theme:
        type: string
  Trend1Res:
    type: object
    properties:
      data:
        type: array
        properties:
          year:
            type: string
          num:
            type: integer
  Trend2Req:
    type: object
    properties:
      industry:
        type: string
      area:
        type: string
      applicant:
        type: string
      key:
        type: string
      theme:
        type: string
  Trend2Res:
    type: object
    properties:
      data:
        type: array
        properties:
          year:
            type: string
          authorization_num:
            type: integer
          apply_num:
            type: integer
          proportion:
            type: number
            format: float
  ApplicantReq:
    type: object
    properties:
      industry:
        type: string
      area:
        type: string
      applicant:
        type: string
      key:
        type: string
      theme:
        type: string
  ApplicantRes:
    type: object
    properties:
      data:
        type: array
        properties:
          applicant:
            type: string
          num:
            type: integer
  AreaReq:
    type: object
    properties:
      industry:
        type: string
      applicant:
        type: string
      key:
        type: string
      theme:
        type: string
  AreaRes:
    type: object
    properties:
      years:
        type: array
        properties:
          year:
            type: string
      areas:
        type: array
        properties:
          area:
            type: string
          data:
            type: array
            properties:
              num:
                type: integer
  TypeReq:
    type: object
    properties:
      industry:
        type: string
      applicant:
        type: string
      key:
        type: string
      theme:
        type: string
  TypeRes:
    type: object
    properties:
      data:
        type: array
        properties:
          type:
            type: string
          num:
            type: integer
  PatentReportReq:
    type: object
    properties:
      user_id:
        type: string
      key:
        type: string
      industry:
        type: string
      area:
        type: string
      applicant:
        type: string
  PatentReportRes:
    type: object
    properties:
      data:
        $ref: '#/definitions/PatentReportRes_data'
    example:
      data:
        id: 0
        title: 报告标题
  PatentReportRes_data:
    type: object
    properties:
      id:
        type: integer
      title:
        type: string
    example:
      id: 0
  PatentReportDetailReq:
    type: object
    properties:
      report_id:
        type: integer
      type:
        type: string
      sub_title:
        type: string
      content:
        type: string
      data:
        type: string
  PatentReportDetailRes:
    type: object
    properties:
      data:
        $ref: '#/definitions/PatentReportDetailRes_data'
    example:
      data:
        id: 0
  PatentReportDetailRes_data:
    type: object
    properties:
      id:
        type: integer
    example:
      id: 0

  TechnologyReq:
    type: object
    properties:
      industry:
        type: string
      area:
        type: string
      key:
        type: string
      theme:
        type: string
  TechnologyRes:
    type: object
    properties:
      data:
        type: array
        properties:
          class:
            type: string
          num:
            type: integer
  ConcentrationReq:
    type: object
    properties:
      industry:
        type: string
      area:
        type: string
      applicant:
        type: string
      key:
        type: string
      theme:
        type: string
  ConcentrationRes:
    type: object
    properties:
      data:
        type: array
        properties:
          year:
            type: string
          proportion:
            type: number
            format: float
  ListReq:
    type: object
    properties:
      user_id:
        type: string
  ListRes:
    type: object
    properties:
      data:
        type: array
        properties:
          id:
            type: integer
          title:
            type: string
          update_time:
            type: string
          status:
            type: integer
          is_deleted:
            type: integer
          batch_id:
            type: integer
  DetailReq:
    type: object
    properties:
      id:
        type: integer
  DetailRes:
    type: object
    properties:
      data:
        type: array
        properties:
          type:
            type: string
          sub_title:
            type: string
          content:
            type: string
          data:
            type: string
          status:
            type: integer
          is_deleted:
            type: integer
  DeleteReq:
    type: object
    properties:
      ids:
        type: array
        items:
          type: integer