openapi: 3.0.1
info:
  title: API Demo
  version: "1.0"
servers:
- url: /v1
paths:
  /users:
    post:
      summary: Create a new user
      operationId: create_user
      requestBody:
        content:
          '*/*':
            schema:
              $ref: '#/components/schemas/User'
        required: true
      responses:
        "201":
          description: User created
          content: {}
        "400":
          description: Invalid input
          content: {}
      x-codegen-request-body-name: user
      x-openapi-router-controller: swagger_server.controllers.default_controller
components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        email:
          type: string
x-original-swagger-version: "2.0"

