openapi: 3.0.1
info:
  title: API Demo
  version: "1.0"
servers:
- url: /v1
paths:
  /patent/trend1:
    post:
      summary: 专利趋势1
      operationId: patent_trend1
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Trend1Req'
        required: true
      responses:
        "200":
          description: success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Trend1Res'
        "400":
          description: Invalid input
          content: {}
      x-codegen-request-body-name: body
      x-openapi-router-controller: swagger_server.controllers.default_controller
  /patent/trend2:
    post:
      summary: 专利趋势2
      operationId: patent_trend2
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Trend2Req'
        required: true
      responses:
        "200":
          description: success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Trend2Res'
        "400":
          description: Invalid input
          content: {}
      x-codegen-request-body-name: body
      x-openapi-router-controller: swagger_server.controllers.default_controller
  /patent/applicant:
    post:
      summary: 申请人分析
      operationId: patent_applicant
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ApplicantReq'
        required: true
      responses:
        "200":
          description: success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApplicantRes'
        "400":
          description: Invalid input
          content: {}
      x-codegen-request-body-name: body
      x-openapi-router-controller: swagger_server.controllers.default_controller
  /patent/area:
    post:
      summary: 地域分析
      operationId: patent_area
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AreaReq'
        required: true
      responses:
        "200":
          description: success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AreaRes'
        "400":
          description: Invalid input
          content: {}
      x-codegen-request-body-name: body
      x-openapi-router-controller: swagger_server.controllers.default_controller
  /patent/type:
    post:
      summary: 地域分析
      operationId: patent_type
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TypeReq'
        required: true
      responses:
        "200":
          description: success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TypeRes'
        "400":
          description: Invalid input
          content: {}
      x-codegen-request-body-name: body
      x-openapi-router-controller: swagger_server.controllers.default_controller
  /patent/technology:
    post:
      summary: 技术构成分析
      operationId: patent_technology
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TechnologyReq'
        required: true
      responses:
        "200":
          description: success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TechnologyRes'
        "400":
          description: Invalid input
          content: {}
      x-codegen-request-body-name: body
      x-openapi-router-controller: swagger_server.controllers.default_controller
  /patent/concentration:
    post:
      summary: 集中度分析
      operationId: patent_concentration
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ConcentrationReq'
        required: true
      responses:
        "200":
          description: success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConcentrationRes'
        "400":
          description: Invalid input
          content: {}
      x-codegen-request-body-name: body
      x-openapi-router-controller: swagger_server.controllers.default_controller
components:
  schemas:
    Trend1Req:
      type: object
      properties:
        industry:
          type: string
        area:
          type: string
        applicant:
          type: string
        key:
          type: string
        theme:
          type: string
    Trend1Res:
      type: object
      properties:
        data:
          $ref: '#/components/schemas/Trend1Res_data'
      example:
        data:
          year: year
          num: 0
    Trend2Req:
      type: object
      properties:
        industry:
          type: string
        area:
          type: string
        applicant:
          type: string
        key:
          type: string
        theme:
          type: string
    Trend2Res:
      type: object
      properties:
        data:
          $ref: '#/components/schemas/Trend2Res_data'
      example:
        data:
          proportion: 1.4658129
          year: year
          apply_num: 6
          authorization_num: 0
    ApplicantReq:
      type: object
      properties:
        industry:
          type: string
        area:
          type: string
        applicant:
          type: string
        key:
          type: string
        theme:
          type: string
    ApplicantRes:
      type: object
      properties:
        data:
          $ref: '#/components/schemas/ApplicantRes_data'
      example:
        data:
          num: 0
          applicant: applicant
    AreaReq:
      type: object
      properties:
        industry:
          type: string
        applicant:
          type: string
        key:
          type: string
        theme:
          type: string
    AreaRes:
      type: object
      properties:
        data:
          $ref: '#/components/schemas/AreaRes_data'
      example:
        data:
          area: area
          year: year
          num: 0
    TypeReq:
      type: object
      properties:
        industry:
          type: string
        applicant:
          type: string
        key:
          type: string
        theme:
          type: string
    TypeRes:
      type: object
      properties:
        data:
          $ref: '#/components/schemas/TypeRes_data'
      example:
        data:
          num: 0
          type: type
    TechnologyReq:
      type: object
      properties:
        industry:
          type: string
        area:
          type: string
        key:
          type: string
        theme:
          type: string
    TechnologyRes:
      type: object
      properties:
        data:
          $ref: '#/components/schemas/TechnologyRes_data'
      example:
        data:
          num: 0
          class: class
    ConcentrationReq:
      type: object
      properties:
        industry:
          type: string
        area:
          type: string
        applicant:
          type: string
        key:
          type: string
        theme:
          type: string
    ConcentrationRes:
      type: object
      properties:
        data:
          $ref: '#/components/schemas/ConcentrationRes_data'
      example:
        data:
          proportion: 0.8008282
          year: year
    Trend1Res_data:
      type: object
      properties:
        year:
          type: string
        num:
          type: integer
      example:
        year: year
        num: 0
    Trend2Res_data:
      type: object
      properties:
        year:
          type: string
        authorization_num:
          type: integer
        apply_num:
          type: integer
        proportion:
          type: number
          format: float
      example:
        proportion: 1.4658129
        year: year
        apply_num: 6
        authorization_num: 0
    ApplicantRes_data:
      type: object
      properties:
        applicant:
          type: string
        num:
          type: integer
      example:
        num: 0
        applicant: applicant
    AreaRes_data:
      type: object
      properties:
        year:
          type: string
        area:
          type: string
        num:
          type: integer
      example:
        area: area
        year: year
        num: 0
    TypeRes_data:
      type: object
      properties:
        type:
          type: string
        num:
          type: integer
      example:
        num: 0
        type: type
    TechnologyRes_data:
      type: object
      properties:
        class:
          type: string
        num:
          type: integer
      example:
        num: 0
        class: class
    ConcentrationRes_data:
      type: object
      properties:
        year:
          type: string
        proportion:
          type: number
          format: float
      example:
        proportion: 0.8008282
        year: year
x-original-swagger-version: "2.0"

