openapi: 3.0.1
info:
  title: API Demo
  version: "1.0"
servers:
- url: /v1
paths:
  /users:
    get:
      summary: Get user
      operationId: get_user
      responses:
        "200":
          description: success
          content: {}
      x-openapi-router-controller: swagger_server.controllers.default_controller
components:
  schemas: {}
x-original-swagger-version: "2.0"

